version: "3"
services:
  database:
    image: "mongo"
    container_name: "mongo_db"
    environment:
      MONGO_INITDB_DATABASE: todosapp
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"
